server:
  port: 8080

spring:
  datasource:
    #链接池
    hikari: # https://github.com/brettwooldridge/HikariCP (uses milliseconds for all time values)
      maximumPoolSize: 10 #连接池中允许的最大连接数。缺省值：10
      minimumIdle: 10   #最小空闲连接数量
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000  #一个连接的生命时长（毫秒）

    #数据源1
    db1:
      jdbc-url: jdbc:mysql://104.168.195.152:3306/db1??useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    #数据源2
    db2:
      jdbc-url: jdbc:mysql://104.168.195.152:3306/db2??useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
  mvc:
    view:
      prefix : /WEB-INF/jsp/
      suffix : .jsp




mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml



